CREATE TABLE IF NOT EXISTS meet_state (
  id TINYINT UNSIGNED NOT NULL PRIMARY KEY,
  individual_entries JSON NOT NULL,
  relay_teams JSON NOT NULL,
  draws JSON NOT NULL,
  results JSON NOT NULL,
  timetable_config JSON NULL,
  timetable_rows JSON NULL,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;

INSERT INTO meet_state (id, individual_entries, relay_teams, draws, results, timetable_config, timetable_rows)
VALUES (1, JSON_ARRAY(), JSON_ARRAY(), JSON_OBJECT(), JSON_OBJECT(), NULL, NULL)
ON DUPLICATE KEY UPDATE id = id;

CREATE TABLE IF NOT EXISTS admin_users (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(100) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB;
